"""media assets and tags

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 23:18:36.073720

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_name"), ["name"], unique=True)

    op.create_table(
        "media_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_media_assets_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_assets_storage_key")),
    )
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_assets_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_media_assets_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "post_tags",
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_post_tags_post_id_posts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_post_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_id", "tag_id", name=op.f("pk_post_tags")),
    )
    with op.batch_alter_table("post_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_post_tags_tag_id"), ["tag_id"], unique=False)

    with op.batch_alter_table("post_media", schema=None) as batch_op:
        batch_op.add_column(sa.Column("asset_id", sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f("ix_post_media_asset_id"), ["asset_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_post_media_asset_id_media_assets"),
            "media_assets",
            ["asset_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_media", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_post_media_asset_id_media_assets"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_post_media_asset_id"))
        batch_op.drop_column("asset_id")

    with op.batch_alter_table("post_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_tags_tag_id"))

    op.drop_table("post_tags")
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_assets_owner_id"))
        batch_op.drop_index(batch_op.f("ix_media_assets_created_at"))

    op.drop_table("media_assets")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_name"))

    op.drop_table("tags")
    # ### end Alembic commands ###
