"""likes saves comments follows

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 23:28:59.197263

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.Uuid(), nullable=False),
        sa.Column("followee_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("follower_id <> followee_id", name=op.f("ck_follows_no_self_follow")),
        sa.ForeignKeyConstraint(
            ["followee_id"],
            ["users.id"],
            name=op.f("fk_follows_followee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name=op.f("fk_follows_follower_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("follower_id", "followee_id", name=op.f("pk_follows")),
    )
    with op.batch_alter_table("follows", schema=None) as batch_op:
        batch_op.create_index(
            "ix_follows_followee_created", ["followee_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_follows_follower_created", ["follower_id", "created_at"], unique=False
        )

    op.create_table(
        "comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_comments_post_id_posts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_author_id"), ["author_id"], unique=False)
        batch_op.create_index(
            "ix_comments_post_created", ["post_id", "created_at", "id"], unique=False
        )

    op.create_table(
        "post_likes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_post_likes_post_id_posts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_post_likes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "post_id", name=op.f("pk_post_likes")),
    )
    with op.batch_alter_table("post_likes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_post_likes_post_id"), ["post_id"], unique=False)

    op.create_table(
        "post_saves",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_post_saves_post_id_posts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_post_saves_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "post_id", name=op.f("pk_post_saves")),
    )
    with op.batch_alter_table("post_saves", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_post_saves_post_id"), ["post_id"], unique=False)
        batch_op.create_index("ix_post_saves_user_created", ["user_id", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_saves", schema=None) as batch_op:
        batch_op.drop_index("ix_post_saves_user_created")
        batch_op.drop_index(batch_op.f("ix_post_saves_post_id"))

    op.drop_table("post_saves")
    with op.batch_alter_table("post_likes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_likes_post_id"))

    op.drop_table("post_likes")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index("ix_comments_post_created")
        batch_op.drop_index(batch_op.f("ix_comments_author_id"))

    op.drop_table("comments")
    with op.batch_alter_table("follows", schema=None) as batch_op:
        batch_op.drop_index("ix_follows_follower_created")
        batch_op.drop_index("ix_follows_followee_created")

    op.drop_table("follows")
    # ### end Alembic commands ###
