"""stories

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 23:41:45.965688

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=240), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("cover_asset_id", sa.Uuid(), nullable=True),
        sa.Column("location_text", sa.String(length=120), nullable=True),
        sa.Column("place_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_stories_author_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["cover_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_stories_cover_asset_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stories")),
    )
    with op.batch_alter_table("stories", schema=None) as batch_op:
        batch_op.create_index(
            "ix_stories_author_updated", ["author_id", "updated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stories_cover_asset_id"), ["cover_asset_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stories_place_id"), ["place_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stories_slug"), ["slug"], unique=True)
        batch_op.create_index(
            "ix_stories_status_published", ["status", "published_at", "id"], unique=False
        )

    op.create_table(
        "story_likes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("story_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
            name=op.f("fk_story_likes_story_id_stories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_story_likes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "story_id", name=op.f("pk_story_likes")),
    )
    with op.batch_alter_table("story_likes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_story_likes_story_id"), ["story_id"], unique=False)

    op.create_table(
        "story_media",
        sa.Column("story_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["media_assets.id"],
            name=op.f("fk_story_media_asset_id_media_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
            name=op.f("fk_story_media_story_id_stories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("story_id", "asset_id", name=op.f("pk_story_media")),
    )
    with op.batch_alter_table("story_media", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_story_media_asset_id"), ["asset_id"], unique=False)

    op.create_table(
        "story_saves",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("story_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
            name=op.f("fk_story_saves_story_id_stories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_story_saves_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "story_id", name=op.f("pk_story_saves")),
    )
    with op.batch_alter_table("story_saves", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_story_saves_story_id"), ["story_id"], unique=False)
        batch_op.create_index(
            "ix_story_saves_user_created", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "story_tags",
        sa.Column("story_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
            name=op.f("fk_story_tags_story_id_stories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_story_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("story_id", "tag_id", name=op.f("pk_story_tags")),
    )
    with op.batch_alter_table("story_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_story_tags_tag_id"), ["tag_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("story_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_story_tags_tag_id"))

    op.drop_table("story_tags")
    with op.batch_alter_table("story_saves", schema=None) as batch_op:
        batch_op.drop_index("ix_story_saves_user_created")
        batch_op.drop_index(batch_op.f("ix_story_saves_story_id"))

    op.drop_table("story_saves")
    with op.batch_alter_table("story_media", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_story_media_asset_id"))

    op.drop_table("story_media")
    with op.batch_alter_table("story_likes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_story_likes_story_id"))

    op.drop_table("story_likes")
    with op.batch_alter_table("stories", schema=None) as batch_op:
        batch_op.drop_index("ix_stories_status_published")
        batch_op.drop_index(batch_op.f("ix_stories_slug"))
        batch_op.drop_index(batch_op.f("ix_stories_place_id"))
        batch_op.drop_index(batch_op.f("ix_stories_cover_asset_id"))
        batch_op.drop_index("ix_stories_author_updated")

    op.drop_table("stories")
    # ### end Alembic commands ###
