"""profile avatar and cover

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04 23:57:52.072629

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar_asset_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("cover_asset_id", sa.Uuid(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_profiles_avatar_asset_id"), ["avatar_asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_profiles_cover_asset_id"), ["cover_asset_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_profiles_avatar_asset_id_media_assets"),
            "media_assets",
            ["avatar_asset_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_profiles_cover_asset_id_media_assets"),
            "media_assets",
            ["cover_asset_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_profiles_cover_asset_id_media_assets"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_profiles_avatar_asset_id_media_assets"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_profiles_cover_asset_id"))
        batch_op.drop_index(batch_op.f("ix_profiles_avatar_asset_id"))
        batch_op.drop_column("cover_asset_id")
        batch_op.drop_column("avatar_asset_id")

    # ### end Alembic commands ###
