"""places

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 00:12:34.553985

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_local", sa.String(length=120), nullable=True),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cover_url", sa.String(length=2048), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=False),
        sa.Column("division", sa.String(length=80), nullable=True),
        sa.Column("district", sa.String(length=80), nullable=True),
        sa.Column("upazila", sa.String(length=80), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
    )
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.create_index("ix_places_division_district", ["division", "district"], unique=False)
        batch_op.create_index("ix_places_lat_lng", ["latitude", "longitude"], unique=False)
        batch_op.create_index(batch_op.f("ix_places_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_places_slug"), ["slug"], unique=True)

    # place_id used to be an unconstrained reserved column; nothing could set it before
    # this migration, but clear it defensively so the new foreign keys always apply.
    op.execute("UPDATE posts SET place_id = NULL WHERE place_id IS NOT NULL")
    op.execute("UPDATE stories SET place_id = NULL WHERE place_id IS NOT NULL")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_posts_place_id_places"),
            "places",
            ["place_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("stories", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_stories_place_id_places"),
            "places",
            ["place_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stories", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_stories_place_id_places"), type_="foreignkey")

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_posts_place_id_places"), type_="foreignkey")

    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_places_slug"))
        batch_op.drop_index(batch_op.f("ix_places_name"))
        batch_op.drop_index("ix_places_lat_lng")
        batch_op.drop_index("ix_places_division_district")

    op.drop_table("places")
    # ### end Alembic commands ###
